Mc consistentoutput
ONSdigital/es-strata-sg pull request #23
Opened 2019-12-04 10:13 UTC by Piwington

2019-12-04 13:49 UTC, thomashenson commented on tests/test_strata.py
> +                        print(response)
Remove print

2019-12-04 13:49 UTC, thomashenson requested changes
Need to remove print from code

2019-12-04 16:00 UTC, KrisRogos approved these changes
Looks good

2019-12-05 10:52 UTC, thomashenson approved these changes

2019-12-05 14:15 UTC, merged